### ISSUE TITLE
Better status

### ISSUE THREAD

**Issue by pergolafabio** [scheidtdav/homeassistant-kostal-piko#12]
Hi,

not all status are properly in line with HA, i know you added some new recently, i was able to capture event "7' , i looked in webpage

Event 7 = (Isolatie meting) (dutch translation) => in german => Isolationsmessung

I also see sometimes event 8 , but was not able to capture it yet from webserver

**Comment by pergolafabio** [comment]
Ok, I was able to check the status again today, with proper translation...

7: insulation measurement / Isolationsmessung
8: waiting time active / wartezeit aktiv

Maybe you can add those too, gives better status in HA

About 6, never had it yet, maybe it's "error" or something... I hope I don't see that event anytime soon :-)

**Comment by scheidtdav** [comment]
Thanks @pergolafabio ,

I have added the states and will quickly do a new release. Cheers!

**Comment by pergolafabio** [comment]
great, thnx! :-)
