### ISSUE TITLE
Not recognized as HASS-IO Integration

### ISSUE THREAD

**Issue by wolfei87** [scheidtdav/homeassistant-kostal-piko#14]
When adding the git url to the add-on store repository, a failure "https://github.com/scheidtdav/homeassistant-kostal-piko is not a valid add-on repository" appears.

Am I missing a file or information? I used the repository add-on to tool before and it worked. However, in the meantime I use HA 11.5 core and the latest UI.

Protocol:
Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:138
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 17:11:26 (1 occurrences)
Last logged: 17:11:26

Failed to to call /store/repositories - https://github.com/scheidtdav/homeassistant-kostal-piko is not a valid add-on repository

**Comment by scheidtdav** [comment]
Hi 👋 
It looks like you were trying to add this to the Supervisor repositories. This is not an add-on repository for the supervisor.
You may either add this to your Home Assistant using the source code (which I do not recommend) or you will have to use [HACS](https://hacs.xyz) to be able to add this as a custom repository to your installation.
You can find documentation for that here: https://hacs.xyz/docs/faq/custom_repositories/

Hope that helps :-)

**Comment by wolfei87** [comment]
thank you for the hint. still to learn a lot. managed to get it installed!

**Comment by scheidtdav** [comment]
Hey,

I have created a new issue for this. Don't worry, for now those are just warnings about deprecations. It will work like this until January 2025. I'll take care of those warnings in the next release :)

**Comment by Pantalooney** [comment]
Hi @scheidtdav, is this still on your radar? January 2025 is not far away anymore. :)
