### ISSUE TITLE
PIKO 12 is supported

### ISSUE THREAD

**Issue by DooMMasteR** [scheidtdav/homeassistant-kostal-piko#16]
I just wanted to report the integration working fine on our PIKO 12.
![image](https://github.com/scheidtdav/homeassistant-kostal-piko/assets/204733/54bcf283-d8fd-4024-ae62-cdcc5a0ed8ff)

**Comment by scheidtdav** [comment]
Sweet, thanks for letting me! I've updated the README accordingly.

Happy automating!
