### ISSUE TITLE
Blank fields when adding integration

### ISSUE THREAD

**Issue by molle1996** [scheidtdav/homeassistant-kostal-piko#17]
Hi. 
When i try to follow the instructions and installing it using HACS, i get the following when i try to add to as an integration. 
Can you please describe what needs to be filled out at the different fields? 

![image](https://github.com/user-attachments/assets/437c005a-029f-4f90-a30e-3da04a9cd175)

**Comment by molelightn** [comment]
login data from your inverter. IP Adress, username and password. The same you use for login on your inverters webbrowser page.

**Comment by scheidtdav** [comment]
Thats perfectly correct @molelightn, thanks for clarifying!
I hope that works for you @molle1996, let me know if I can close this.

The bug has already been reported to #6

**Comment by melvinisken** [comment]
I experienced the same. I wanted to add that the IP is not enough to be put in, it needs to be the full URL including http://

**Comment by scheidtdav** [comment]
Good point @melvinisken, that should be included in the description for the field.
I have updated #6 to include your comment. Please drop any additional information into that issue.

Closing this as it seems to be working (once you know what to put it 😅 )
