### ISSUE TITLE
Add device to compatibility list

### ISSUE THREAD

**Issue by melvinisken** [scheidtdav/homeassistant-kostal-piko#18]
I didn't know where to put it, but I wanted to mention that you can add the Kostal Piko 4.2 inverter to your compatibility list. It just needs to run the latest firmware that has been released for it (the device is discontinued, I think):
![grafik](https://github.com/user-attachments/assets/83e3d6cc-4d7c-417a-8879-52962f7a4e5b)

**Comment by scheidtdav** [comment]
This is precisely where to put it :) Thanks for the info, much appreciated. I have updated the README.
