### ISSUE TITLE
Short description

### ISSUE THREAD

**Issue by tunguskar** [scheidtdav/homeassistant-kostal-piko#2]
Hi,

First of all thanks for your work!

I wanted to add the folder to the custom_components. Can you give a short example how to add this component to the configuration.yaml?

Kind Regards

**Comment by scheidtdav** [comment]
Hey,

thanks for your interest in the project.
I've recently started to refactor this project to eventually have it in Home Assistant Core.
Not sure how long that will still take, so I cannot promise anything.
I am posting updates [here](https://community.home-assistant.io/t/kostal-piko-10-ba-custom-sensor/345038/7).

In the meantime, if you want to use this as a custom component (which I am currently doing myself as well), I have just created a [tag called prototype](https://github.com/scheidtdav/homeassistant-kostal-piko/tree/prototype), which marks an earlier version of this repository.
That version also contains a README file with an example for a configuration.yaml entry.
You can download and use that if you like.

Hope that helps, cheers :raised_hands:

**Comment by tunguskar** [comment]
Thanks for the answer. I tried to add the folder to cusomt_components. did a complete reboot of home assistant. When I now add the  configuration to configuration.yaml. it says, that the kosal_piko component is not available. Do you know this problem?

**Comment by scheidtdav** [comment]
Hi, 

I wasn't super sure about how it worked again, so I checked my current configuration:
![image](https://user-images.githubusercontent.com/20562255/139707511-c2a3dacb-1d2e-4985-8fda-95bc2b75c16e.png)

Inside the configuration.yaml, the sensor is configured as shown in the README of the tag.
Here is a minimal example:
```yaml
sensor:
  - platform: kostal_piko
    host: !secret kostal_host
    monitored_conditions:
      - battery_charge
```

Did you create the kostal_piko folder inside the custom_components folder?
If so, it should work.. At least I cannot think of anything else that requires configuration.

**Comment by tunguskar** [comment]
Strange behavior. Im getting always this message: Platform error sensor.kostal_piko - Integration 'kostal_piko' not found.

<img width="152" alt="image" src="https://user-images.githubusercontent.com/2837624/139748706-5c4c5fe1-620b-4010-8c25-9a035dace707.png">

Nevertheless, thanks for the support. Maybe I have to google a little bit arround

**Comment by scheidtdav** [comment]
Sure thing, sorry I can't help much further.
Best of luck finding the issue!
