### ISSUE TITLE
Fix Config Flow Data Entry

### ISSUE THREAD

**Issue by scheidtdav** [scheidtdav/homeassistant-kostal-piko#6]
During installation, the following dialog is shown:
![image](https://github.com/scheidtdav/homeassistant-kostal-piko/assets/20562255/b4fa6dea-acfc-4b20-9549-052cd76a6d4c)

It should explain to the user, that host, username and password are supposed to be entered.

As commented [here](https://github.com/scheidtdav/homeassistant-kostal-piko/issues/17#issuecomment-2272765220) it should also at least explain to include the http schema.

**Comment by pergolafabio** [comment]
Hi, my old dcs was replaced with a 5.5 BA model, so i needed to use the newer api... Installed this one, but on the config flow the titles were just blanc, so it was a little bit of guessing :-)

Anyway , i think this issue should be reopened? Probability something to do with the dictionaries?

**Comment by pergolafabio** [comment]
Here is a screen:

![Screenshot_20231213-082033](https://github.com/scheidtdav/homeassistant-kostal-piko/assets/43251136/39ce81b6-bae2-490b-867d-53fd593af86f)

**Comment by scheidtdav** [comment]
Hey @pergolafabio, 

Agreed, that needs to be fixed.
Thanks for reporting!

**Comment by pergolafabio** [comment]
Thnx , and appreciate this version, works quite well!

Only the status, when kostal is "off", I see the status entity in "unknown" state? Shouldn't that be something like power off ?

**Comment by scheidtdav** [comment]
> Only the status, when kostal is "off", I see the status entity in "unknown" state? Shouldn't that be something like power off ?

Well yes and no. I was not able to pin point exactly which state corresponds to what value reported by the inverter.
As you can see [here](https://github.com/scheidtdav/homeassistant-kostal-piko/blob/main/custom_components/kostal_piko/const.py#L31) there are two unknown values for two different states that the inverter may report.
If you happen to be able to say exactly which one is "off" and possibly even what the other one means, I am happy to implement that. In that case, lets move that to a separate issue though :)
