### ISSUE TITLE
cannot_connect

### ISSUE THREAD

**Issue by TheRealTsevenXD** [scheidtdav/homeassistant-kostal-piko#9]
hello im trying to setup the integration and has run into trouble, firstly the configuration wizard doesnt display any text, and when i insert the values (guessed which was which) i get this message "cannot_connect"

**Comment by scheidtdav** [comment]
Hello,

That sounds strange to me. It is possible that an update to Home Assistant has brought a breaking change.
Could you provide some details please:
- Which version of Home Assistant are you running?
- Can you share a screenshot?

In case you want to try it again, the order of input fields is: Hostname (aka IP address), username and password.


Cheers

**Comment by TheRealTsevenXD** [comment]
I tried again the day after and no problem anymore. Maybe home assistant didn't restart correctly

**Comment by scheidtdav** [comment]
Haha ok, thats possible.
Gald its working for you :)
